export const GET_DATA_HOME_PAGE = "GET_DATA_HOME_PAGE";
export const HAS_DATA_HOME_PAGE = "HAS_DATA_HOME_PAGE";
export const NO_DATA_HOME_PAGE = "NO_DATA_HOME_PAGE";

export const GET_DATA_ABOUT_PAGE = "GET_DATA_ABOUT_PAGE";
export const HAS_DATA_ABOUT_PAGE = "HAS_DATA_ABOUT_PAGE";
export const NO_DATA_ABOUT_PAGE = "NO_DATA_ABOUT_PAGE";

export const GET_DATA_CONTACT_PAGE = "GET_DATA_CONTACT_PAGE";
export const HAS_DATA_CONTACT_PAGE = "HAS_DATA_CONTACT_PAGE";
export const NO_DATA_CONTACT_PAGE = "NO_DATA_CONTACT_PAGE";

export const GET_DATA_MEN_PRODUCT = "GET_DATA_MEN_PRODUCT";
export const HAS_DATA_MEN_PRODUCT = "HAS_DATA_MEN_PRODUCT";
export const NO_DATA_MEN_PRODUCT = "NO_DATA_MEN_PRODUCT";

export const GET_DATA_WOMEN_PRODUCT = "GET_DATA_WOMEN_PRODUCT";
export const HAS_DATA_WOMEN_PRODUCT = "HAS_DATA_WOMEN_PRODUCT";
export const NO_DATA_WOMEN_PRODUCT = "NO_DATA_WOMEN_PRODUCT";

export const GET_DATA_KIDS_PRODUCT = "GET_DATA_KIDS_PRODUCT";
export const HAS_DATA_KIDS_PRODUCT = "HAS_DATA_KIDS_PRODUCT";
export const NO_DATA_KIDS_PRODUCT = "NO_DATA_KIDS_PRODUCT";

export const GET_DATA_DIGITAL_PRODUCT = "GET_DATA_DIGITAL_PRODUCT";
export const HAS_DATA_DIGITAL_PRODUCT = "HAS_DATA_DIGITAL_PRODUCT";
export const NO_DATA_DIGITAL_PRODUCT = "NO_DATA_DIGITAL_PRODUCT";

export const GET_DATA_OTHER_SERVICES_PRODUCT =
    "GET_DATA_OTHER_SERVICES_PRODUCT";
export const HAS_DATA_OTHER_SERVICES_PRODUCT =
    "HAS_DATA_OTHER_SERVICES_PRODUCT";
export const NO_DATA_OTHER_SERVICES_PRODUCT = "NO_DATA_OTHER_SERVICES_PRODUCT";

export const GET_DATA_FURNITURE_PRODUCT = "GET_DATA_FURNITURE_PRODUCT";
export const HAS_DATA_FURNITURE_PRODUCT = "HAS_DATA_FURNITURE_PRODUCT";
export const NO_DATA_FURNITURE_PRODUCT = "NO_DATA_FURNITURE_PRODUCT";

export const GET_DATA_MY_ACCOUNT = "GET_DATA_MY_ACCOUNT";
export const HAS_DATA_MY_ACCOUNT = "HAS_DATA_MY_ACCOUNT";
export const NO_DATA_MY_ACCOUNT = "NO_DATA_MY_ACCOUNT";

export const GET_DATA_CARTS = "GET_DATA_CARTS";
export const HAS_DATA_CARTS = "HAS_DATA_CARTS";
export const NO_DATA_CARTS = "NO_DATA_CARTS";

export const GET_DATA_CHECKOUT = "GET_DATA_CHECKOUT";
export const HAS_DATA_CHECKOUT = "HAS_DATA_CHECKOUT";
export const NO_DATA_CHECKOUT = "NO_DATA_CHECKOUT";

export const CART_INCREMENT = "CART_INCREMENT";
export const CART_DECREMENT = "CART_DECREMENT";

export const VIEW_DETAILS = "VIEW_DETAILS";
